[versions]
agp = "8.3.2"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.7.0"
composeBom = "2024.04.01"
material3Android = "1.2.1"
coil = "2.6.0"
ksp = "1.9.10-1.0.13"
hiltCompiler = "2.49"
retrofit = "2.9.0"
navigation = "2.7.7"
hiltNavCompose = "1.2.0"
firebaseBom = "32.8.1"
mockito = "5.11.0"
kotlinxCoroutinesTest = "1.8.1-Beta"
gmsGoogleServices = "4.4.0"
hiltTest = "2.49"
mockitoKotlin = "5.3.1"
gson = "2.8.2"
room = "2.6.1"
roomTest = "2.4.0"
worker = "2.9.0"
coroutinesCore = "1.8.1-Beta"
coreKtxVersion = "1.5.0"
junitKtx = "1.1.5"
runner = "1.6.0-alpha07"
roboeletric = "4.12"
googleFonts  = "1.3.2"

[libraries]
roboeletric = { group = "org.robolectric", name = "robolectric", version.ref = "roboeletric"}
android-test-rules = { group = "androidx.test", name = "rules", version.ref = "coreKtxVersion"}
android-test-core = { group = "androidx.test", name = "core", version.ref = "coreKtxVersion"}
androidTestRunner = { group = "androidx.test", name = "runner", version.ref = "runner"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Android" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltCompiler"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltCompiler"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}
worker-coroutines = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "worker" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCore"}

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "roomTest"}

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
navigation-compose-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavCompose" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito"}
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin"}
google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "googleFonts"}
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
dagger-hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltTest"}
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
daggerHiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltCompiler" }
gmsGoogleServices = { id = "com.google.gms.google-services", version.ref = "gmsGoogleServices" }